version: '3.8'

services:
  neonhub-api:
    image: neonhub/backend
    build: .
    ports:
      - '3001:3001'
    depends_on:
      - neonhub-db
    networks:
      - neonhub-network
    env_file:
      - .env
    restart: unless-stopped

  neonhub-db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: neonhub
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: neonhub
    ports:
      - '5432:5432'
    volumes:
      - neonhub-data:/var/lib/postgresql/data
    networks:
      - neonhub-network
    restart: unless-stopped

networks:
  neonhub-network:
    driver: bridge

volumes:
  neonhub-data:
    driver: local
