apiVersion: v2
name: neonhub
description: A Helm chart for NeonHub AI Marketing Automation Platform
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: ~12.5.8
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: ~17.9.2
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled 