services:
  redis:
    image: redis:7-alpine
    container_name: neonhub-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    command: ['redis-server', '--save', '60', '1', '--loglevel', 'warn']
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  redis-data:
    driver: local
