version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: neonhub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 10s
      retries: 5

  # Redis Cache & Message Broker
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Backend API Service
  backend:
    build:
      context: ./backend
      target: ${NODE_ENV:-development}
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - '${BACKEND_PORT:-5001}:${PORT:-5000}'
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-neonhub}?schema=public
      - REDIS_URL=redis://redis:6379
      - PORT=${PORT:-5000}
      - JWT_SECRET=${JWT_SECRET:-dev_jwt_secret}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CLIENT_URL=http://localhost:3000
      - CORS_ORIGIN=http://localhost:3000
    networks:
      - neonhub_network
    restart: unless-stopped
    command: sh -c "npm run prisma:migrate:deploy && npm run dev"

  # Orchestrator Service
  orchestrator:
    build: ./services/orchestrator
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      PORT: 3030
      REDIS_URL: redis://redis:6379
    ports:
      - "3030:3030"

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      target: ${NODE_ENV:-development}
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - NEXT_PUBLIC_API_URL=http://localhost:${BACKEND_PORT:-5001}
    depends_on:
      - backend
    networks:
      - neonhub_network
    restart: unless-stopped

networks:
  neonhub_network:
    driver: bridge

volumes:
  redis_data: {}
